### ISSUE TITLE
Rewrite in rust

### ISSUE THREAD

**Issue by boring-dragon** [Oreofreakshake/E-sportJS#1]

**Comment by Oreofreakshake** [comment]
I'll rewrite it from assembly

**Comment by boring-dragon** [comment]
Can this scale?. I am really worried about performance. I think its best to split this into 5 repo's and deploy each individually to increase performance and extendibility

**Comment by Oreofreakshake** [comment]
I will use a different repo for every component, will that solve the problem?

**Comment by boring-dragon** [comment]
This seems like the only option. Good idea!
